# Generated by Django 4.1.3 on 2022-11-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='man-person-icon.png', upload_to='profile_pics'),
        ),
    ]
